const wordList = [
  {
    word: 'alt',
    hint: `<img src="notaweather.png" ▢▢▢="notaweather Logo">`,
    guessed: `<img src="notaweather.png" alt="notaweather Logo">`,
    task: 'Specify an alternate text for the image',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'script',
    hint: `<▢▢▢▢▢▢ src="module.js"></▢▢▢▢▢▢>`,
    guessed: `<script src="module.js"></script>`,
    task: 'Connect JavaScript file "module.js"',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_scripts.asp`,
  },
  {
    word: 'code',
    hint: `<p>Code example: <▢▢▢▢>let person;</▢▢▢▢></p>`,
    guessed: `<p>Code example: <code>let person;</code></p>`,
    task: 'Define the text "let person;" as programming code',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_computercode_elements.asp`,
  },
  {
    word: 'input',
    hint: `<▢▢▢▢▢ type="button" value="OK">`,
    guessed: `<input type="button" value="OK">`,
    task: 'Make a field where the user can enter data with the type "button" and the value "OK"',
    hard: 1,
    helper: `https://www.w3schools.com/tags/tag_input.asp`,
  },
  {
    word: 'method',
    hint: `<form action="/action_page.php" ▢▢▢▢▢▢="post">`,
    guessed: `<form action="/action_page.php" method="post">`,
    task: 'Specify that the form is submitted using the "POST"',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_forms_attributes.asp`,
  },
  {
    word: 'textarea',
    hint: `<▢▢▢▢▢▢▢▢ name="note"></▢▢▢▢▢▢▢▢>`,
    guessed: `<textarea name="note"></textarea>`,
    task: 'Create multi-line text input control',
    hard: 1,
    helper: `https://www.w3schools.com/tags/tag_textarea.asp`,
  },
  {
    word: 'maxlength',
    hint: `<input type="text" ▢▢▢▢▢▢▢▢▢="40">`,
    guessed: `<input type="text" maxlength="40">`,
    task: 'Set the max numbers of characters allowed in the input field to 40',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_form_attributes.asp`,
  },
  {
    word: 'width',
    hint: `<iframe src="https://www.w3.com" ▢▢▢▢▢="500"></iframe>`,
    guessed: `<iframe src="https://www.w3.com" width="500"></iframe>`,
    task: 'Use an iframe attribute to make the iframe 500 pixels wide',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_iframe.asp`,
  },

  {
    word: 'class',
    hint: `<p ▢▢▢▢▢="special">My paragraph</p>`,
    guessed: `<p class="special">My paragraph</p>`,
    task: 'Create selector for adding styles',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_classes.asp`,
  },
  {
    word: 'li',
    hint: `<ul><▢▢>Coffee</▢▢></ul>`,
    guessed: `<ul><li>Coffee</li></ul>`,
    task: `Add a list item with the text "Coffee" inside the <ul>`,
    hard: 1,
    helper: `https://www.w3schools.com/html/html_lists.asp`,
  },
  {
    word: 'src',
    hint: `<img ▢▢▢="smiley.gif">`,
    guessed: `<img src="smiley.gif">`,
    task: 'Add the correct HTML attribute to display the "smiley.gif" image',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_images.asp`,
  },
  {
    word: 'target',
    hint: `<a href="images.asp" ▢▢▢▢▢▢="_blank">Images</a>`,
    guessed: `<a href="images.asp" target="_blank">Images</a>`,
    task: 'Use the correct HTML attribute to make the link open in a new window',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_links.asp`,
  },
  {
    word: 'q',
    hint: `<p>I am so <▢>cool<▢> in this</p>`,
    guessed: `<p>I am so <q>cool<q> in this</p>`,
    task: 'Use an HTML element to add quotation marks around the letters "cool"',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_quotation_elements.asp`,
  },
  {
    word: 'style',
    hint: `<p ▢▢▢▢▢="color:blue;">This is a paragraph.</p>`,
    guessed: `<p style="color:blue;">This is a paragraph.</p>`,
    task: `Use the correct HTML attribute, and CSS, to set the color of the paragraph to "blue"`,
    hard: 1,
    helper: `https://www.w3schools.com/html/html_styles.asp`,
  },
  {
    word: 'br',
    hint: `<p>My Bonnie lies<▢▢>over the ocean.</p>`,
    guessed: `<p>My Bonnie lies<br>over the ocean.</p>`,
    task: 'Add a line break in the middle of the paragraph',
    hard: 1,
    helper: `https://www.w3schools.com/TAGS/tag_br.asp`,
  },
  {
    word: 'href',
    hint: `<a ▢▢▢▢="https://www.notaweather.live">Weather Website</a>`,
    guessed: `<a href="https://www.notaweather.live">Weather Website</a>`,
    task: 'Make the element below into a link that goes to "https://www.notaweather.live"',
    hard: 1,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'aim',
    hint: 'a purpose or intention',
    task: 'sample text3',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'ebay',
    hint: 'online shopping site',
    task: 'sample text6',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'golang',
    hint: 'programming language',
    task: 'sample text7',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'coding',
    hint: 'related to programming',
    task: 'sample text8',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'matrix',
    hint: 'science fiction movie',
    task: 'sample text9',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'bugs',
    hint: 'related to programming',
    task: 'sample text10',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'avatar',
    hint: 'epic science fiction film',
    task: 'sample text11',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'gif',
    hint: 'a file format for image',
    task: 'sample text12',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'mental',
    hint: 'related to the mind',
    task: 'sample text13',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'map',
    hint: 'diagram represent of an area',
    task: 'sample text14',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'chess',
    hint: 'related to an indoor game',
    task: 'sample text17',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'viber',
    hint: 'a social media app',
    task: 'sample text18',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'github',
    hint: 'code hosting platform',
    task: 'sample text19',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'png',
    hint: 'a image file format',
    task: 'sample text20',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'silver',
    hint: 'precious greyish-white metal',
    task: 'sample text21',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'gpu',
    hint: 'computer component',
    task: 'sample text23',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'java',
    hint: 'programming language',
    task: 'sample text24',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'excel',
    hint: 'microsoft product for windows',
    task: 'sample text27',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'mysql',
    hint: 'a relational database system',
    task: 'sample text28',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'nepal',
    hint: 'developing country name',
    task: 'sample text29',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'flute',
    hint: 'a musical instrument',
    task: 'sample text30',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'crypto',
    hint: 'related to bitcoin',
    task: 'sample text31',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'proxy',
    hint: 'related to server application',
    task: 'sample text34',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'email',
    hint: 'electronic exchanging message',
    task: 'sample text35',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'html',
    hint: 'markup language for the web',
    task: 'sample text36',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'idea',
    hint: 'a thought or suggestion',
    task: 'sample text38',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'server',
    hint: 'remote computer or system',
    task: 'sample text39',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'svg',
    hint: 'a vector image format',
    task: 'sample text40',
    hard: 3,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'jpeg',
    hint: 'a image file format',
    task: 'sample text41',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'search',
    hint: 'act to find something',
    task: 'sample text42',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'joker',
    hint: 'psychological thriller film',
    task: 'sample text45',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },

  {
    word: 'photo',
    hint: 'representation of person or scene',
    task: 'sample text47',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
  {
    word: 'nile',
    hint: 'largest river in the world',
    task: 'sample text48',
    hard: 2,
    helper: `https://www.w3schools.com/html/html_attributes.asp`,
  },
]
